[package]
name = "comp31311_langs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8"

[dev-dependencies]
clap = { version = "4.0.22", features = ["derive"] }
